version: 2

models:
  - name: fct_climber_ascents
    columns:
      - name: ascent_id
      - name: user_id
      - name: route_id
      - name: ascent_date
      - name: route_name
      - name: crag
      - name: sector
      - name: country
      - name: sector
      - name: grade_mean
      - name: grade_id
      - name: grade_fra
      - name: climber_age

  - name: dim_climbers
    columns:
      - name: user_id
      - name: number_of_ascents
      - name: first_climb_date
      - name: most_recent_climb_date
      - name: max_grade_climb
      - name: median_grade_climb
      - name: years_climbing
