version: 2

seeds:
  - name: raw_routes
    description: Global routes data from Kaggle.
    columns:
      - name: name_id
        tests:
          - unique
          - not_null
      - name: country
      - name: crag
      - name: sector
      - name: name
      - name: tall_recommend_sum
      - name: grade_mean
      - name: cluster
      - name: rating_tot

  - name: raw_climbers
    description: Climbers data from Kaggle.
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: country
      - name: sex
      - name: height
      - name: weight
      - name: birthdate

  - name: raw_grades_ref
    description: Route grades reference for French grades from Kaggle.
    columns:
      - name: grade_id
        tests:
          - unique
          - not_null
      - name: grade_fra

  - name: raw_ascents
    description: Randomly generated ascents based on climbers and routes, by TC.
    columns:
      - name: ascent_id
        tests:
          - unique
          - not_null
      - name: user_id
      - name: route_id
      - name: ascent_date
