postgres_climbs_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: mysecretpassword
      dbname: climbs_db
      schema: public
