postgres_climbs_db:
  target: dev
  outputs:
    dev:
      type: athena
      s3_staging_dir: s3://dev-dbt-sector-raw-seeds/dbt_out/
      region_name: ap-southeast-2
      schema: dev_dbt_sector
      database: awsdatacatalog
      work_group: primary
      num_retries: 1
